### ISSUE TITLE
Go dependency problem

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-smart-client#119]
I am experiencing issues when building and running a sample application that uses Fabric Smart Client.

I would like to build the application outside the FSC repo and, thus, use FSC as a go dependency. See here my `go.mod`
```
module example.com/irb-flow

go 1.16

require (
	github.com/hyperledger-labs/fabric-smart-client v0.0.0-20210902095918-253c368629f0
	github.com/stretchr/testify v1.7.0
)
```

The full source can be found [here](https://github.com/mbrandenburger/fsc-playground/tree/main/irb-fsc).

When running `go test -v .` I get the following error:
```
  irb-fsc git:(main) ✗ go test -v .
# github.com/hyperledger/fabric/discovery/client
../../../../../../../pkg/mod/github.com/hyperledger/fabric@v1.4.0-rc1.0.20210722174351-9815a7a8f0f7/discovery/client/api.go:43:28: undefined: discovery.ChaincodeCall
../../../../../../../pkg/mod/github.com/hyperledger/fabric@v1.4.0-rc1.0.20210722174351-9815a7a8f0f7/discovery/client/client.go:616:25: undefined: discovery.ChaincodeCall
FAIL	example.com/irb-flow [build failed]
```

Running the same code from the `FSC/integration/fabric` without the `go.mod` seem to work nicely (except of other issues with the code).

**Comment by adecaro** [comment]
Hi @mbrandenburger , 

I have used the following `go.mod` and it runs:

```
go 1.16

replace (
	github.com/fsouza/go-dockerclient => github.com/fsouza/go-dockerclient v1.4.1
	github.com/go-kit/kit => github.com/go-kit/kit v0.7.0
	github.com/hyperledger/fabric => github.com/hyperledger/fabric v1.4.0-rc1.0.20210722174351-9815a7a8f0f7
	github.com/hyperledger/fabric-protos-go => github.com/hyperledger/fabric-protos-go v0.0.0-20201028172056-a3136dde2354
	go.etcd.io/etcd => go.etcd.io/etcd v0.5.0-alpha.5.0.20181228115726-23731bf9ba55
)

require (
	github.com/hyperledger-labs/fabric-smart-client v0.0.0-20210908080609-a1d0dd2cb3c2
	github.com/onsi/gomega v1.14.0 // indirect
	github.com/stretchr/testify v1.7.0

)
```

The error might depend from the fact that you might have in your GOPATH a version of Fabric  and the protos that is not compatible with what FPC compiles against. 

What do you think?

**Comment by mbrandenburger** [comment]
this seems to work for me as well!

**Comment by adecaro** [comment]
can we close the issue?

**Comment by mbrandenburger** [comment]
yes- thanks!
