### ISSUE TITLE
Method `CallView` from package `web` always replace my input's to value: `"hi"`

### ISSUE THREAD

**Issue by alexshehovcov** [hyperledger-labs/fabric-smart-client#147]
FSC-node always get input that contain only `"hi"` value, no matter what input values/data we try to send via method `CallView` from package `web`.
We saw that here looks like value  "hi" is hard-coded https://github.com/hyperledger-labs/fabric-smart-client/blob/b523bd306ea224d3ff8f61645bbc0be13fe54662/platform/view/services/client/web/client.go#L77
P.S. If we change:
 `http.NewRequest(http.MethodPut, url, bytes.NewBuffer([]byte("hi")))`
to
 `http.NewRequest(http.MethodPut, url, bytes.NewBuffer(in))`
we able to get  expected input values/data on FSC node

**Comment by yacovm** [comment]
It's fine, thank you for your contribution.
