### ISSUE TITLE
Test fail on Pingpong example

### ISSUE THREAD

**Issue by RongNK** [hyperledger-labs/fabric-smart-client#168]
Hi,
I am testing FSC on Ubuntu 20.04 and I met this error(my Go version is 1.16.9):
```
Output:
    package usr/local/go/pkg/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20211025113140-e65ee9678b21/integration/fsc/pingpong/cmd/responder: can only use path@version syntax with 'go get' and 'go install' in module-aware mode

```
and finally:
```
Ran 5 of 5 Specs in 39.811 seconds
FAIL! -- 2 Passed | 3 Failed | 0 Pending | 0 Skipped
```

Thank for your work!

**Comment by RongNK** [comment]
I tested by go to integration/fsc/pingpong folder and enter "go test" command.

**Comment by adecaro** [comment]
Hi @RongNK, that's strange because the CI is passing and we use Ubuntu there.
Can you post the logs that you get, please? :)

**Comment by RongNK** [comment]
> Hi @RongNK, that's strange because the CI is passing and we use Ubuntu there. Can you post the logs that you get, please? :)

Hi @adecaro. After digging a bit into the example, i got to know the problem, the problem came from our server environment variable.
This issue can close now. Thank for your attension!
