### ISSUE TITLE
Provide prometheus integration 

### ISSUE THREAD

**Issue by mffrench** [hyperledger-labs/fabric-smart-client#214]
... so that we can monitor some memory stuffs like HEAP, GC etc . See how HLF is providing such monitoring tools for more details.

![image](https://user-images.githubusercontent.com/5983074/150107790-93f4400f-207f-4e97-a665-454e35555339.png)

**Comment by adecaro** [comment]
Interesting task, perfect for the community to pick :)

**Comment by adecaro** [comment]
https://github.com/hyperledger-labs/fabric-smart-client/blob/e001986ecc9fa58707353599bddee31f5dd8b239/platform/view/services/metrics 

done :)
