### ISSUE TITLE
Issue in running the ping-pong sample

### ISSUE THREAD

**Issue by karthiksukumaran** [hyperledger-labs/fabric-smart-client#249]
### Discussed in https://github.com/hyperledger-labs/fabric-smart-client/discussions/248

<div type='discussions-op-text'>

<sup>Originally posted by **karthiksukumaran** March 15, 2022</sup>
Hi All, I am facing issue in running the pingpong example. Getting the below error. Please help 

Please find the below steps, also please find the attached logs 

$ go version
go version go1.17.8 linux/amd64

$ cd $GOPATH/src/github.com/hyperledger-labs/fabric-smart-client/integration/fsc/pingpong

$ go test

**Error**
[Fabric-Smart-Client-Error.log](https://github.com/hyperledger-labs/fabric-smart-client/files/8252618/Fabric-Smart-Client-Error.log)

EndToEnd
/home/blockchain/go/gopath/src/github.com/hyperledger-labs/fabric-smart-client/integration/fsc/pingpong/pingpong_test.go:25
  Network-based Ping pong
  /home/blockchain/go/gopath/src/github.com/hyperledger-labs/fabric-smart-client/integration/fsc/pingpong/pingpong_test.go:96
    load artifact & init clients & successful pingpong [It]
    /home/blockchain/go/gopath/src/github.com/hyperledger-labs/fabric-smart-client/integration/fsc/pingpong/pingpong_test.go:154

    Test Panicked
    Failed to build home/blockchain/go/gopath/src/github.com/hyperledger-labs/fabric-smart-client/integration/fsc/pingpong/cmd/responder:

    Error:
    exit status 1

    Output:
    package home/blockchain/go/gopath/src/github.com/hyperledger-labs/fabric-smart-client/integration/fsc/pingpong/cmd/responder is not in GOROOT (/home/blockchain/go/go/src/home/blockchain/go/gopath/src/github.com/hyperledger-labs/fabric-smart-client/integration/fsc/pingpong/cmd/responder)

    Expected
        <int>: 500
    to equal
        <int>: 200
    /home/blockchain/go/gopath/src/github.com/hyperledger-labs/fabric-smart-client/integration/integration.go:338
</div>
[Fabric-Smart-Client-Error.log](https://github.com/hyperledger-labs/fabric-smart-client/files/8259986/Fabric-Smart-Client-Error.log)

**Comment by adecaro** [comment]
Hi @karthiksukumaran , sorry for my very late reply.

What's your $GOPATH? Looking at log you posted, you should make sure it is set to `/home/blockchain/go/gopath`.

**Comment by mbrandenburger** [comment]
PR #300 updates the README with more information on how to setup `GOPATH`.

I will close this issue. If you still have the issue and additional information don't help, please feel free to re-open! Thanks
