### ISSUE TITLE
The fsc node approver and iou process memory leak, the memory grows to 16G in about 10 minutes under 50-60TPS and exits abnormally

### ISSUE THREAD

**Issue by yaofeiliang** [hyperledger-labs/fabric-smart-client#316]

**Comment by adecaro** [comment]
@yaofeiliang , this is very interesting. Can you give us more information? Do you have profile data that you can share for us to analyze? Do you know where the memory is leaked?

**Comment by mbrandenburger** [comment]
Hi @yaofeiliang 

can you please provide additional information which let me reproduce this issue. I was wondering how you invoke the 50k transactions? How did you measure the memory consumption?

Could you also try to enable monitoring in the IOU topology and share the Grafana logs.
```go
	// Monitoring
	monitoringTopology := monitoring.NewTopology()
	//monitoringTopology.EnableHyperledgerExplorer()
	monitoringTopology.EnablePrometheusGrafana()

	return []api.Topology{
		fabricTopology,
		fscTopology,
		monitoringTopology,
	}
```

Once the network is up and running using `./iou network start --path ./testdata`, you can log into Grafana via your browser on `localhost:3000` as `admin` with the default password `admin`.

The Fabric Backend Dashboard will show you the memory consumption of the FSC nodes and Fabric peers.

To run some workload over time I was testing with the following script but I did not observe any abnormal memory consumption.

```bash
#!/usr/bin/env bash

outFile="out.txt"

for i in {1..1000}; do
  echo "run: $i"
  ./iou view -c ./testdata/fsc/nodes/borrower/client-config.yaml -f create -i "{\"Amount\":10}" > $outFile
  id=$(head -n 1 $outFile | tr -d '"'s)
  ./iou view -c ./testdata/fsc/nodes/borrower/client-config.yaml -f query -i "{\"LinearID\":\"$id\"}"
  ./iou view -c ./testdata/fsc/nodes/lender/client-config.yaml -f query -i "{\"LinearID\":\"$id\"}"
  ./iou view -c ./testdata/fsc/nodes/borrower/client-config.yaml -f update -i "{\"LinearID\":\"$id\",\"Amount\":8}"
done
```

**Comment by yaofeiliang** [comment]
@adecaro @mbrandenburger 
![6711657789789_ pic](https://user-images.githubusercontent.com/31167188/178947186-7e0a5303-d2cf-4c86-ae79-d79ee2a110c5.jpg)
![6701657789662_ pic](https://user-images.githubusercontent.com/31167188/178947295-3d21d925-cc27-466a-88ab-f9bc35f2ce8b.jpg)
![6691657789612_ pic](https://user-images.githubusercontent.com/31167188/178947357-30ba87ae-1aab-45ec-990d-1ecb3b3b4947.jpg)

After executing the script concurrently
number of transactions 2307;
Memory usage:
iou 1.98G;
approver 1.13G;
borrower 1.08G;
lender 609.2M;
and increasing as transactions grow

**Comment by adecaro** [comment]
Hi @yaofeiliang , fantastic data. Thanks a lot for this feedback.
Please, could you check the folder where the FSC node configuration is (`core.yaml`)? There you should be able to find the cpu, memory, and locks profile that are automatically generated when you shut down an FSC node.

I think this can give us additional information :)

**Comment by mbrandenburger** [comment]
@yaofeiliang it seems that the current way of logging the FSC nodes and processes causes this heavy memory usage. Since the IOU sample builds on top of the integration test suite, all logging is kept in memory to allow anaylizing the output of the processes. However, this is not the right way to do that when you have a long running setup with many transactions. We will look into that.

**Comment by yaofeiliang** [comment]
@mbrandenburger Loyal fans look forward to memory problem solved.
