### ISSUE TITLE
Add TxIDStore cache to orion backend

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-smart-client#365]
The Fabric Vault impl supports a TxIDStore cache for better read performance. See https://github.com/hyperledger-labs/fabric-smart-client/blob/main/platform/fabric/core/generic/vault.go#L80

We should add this to the Orion Vault impl as well

**Comment by yajna-pandith** [comment]
Is this still open?

**Comment by adecaro** [comment]
Hi @yajna-pandith , is this something you need for your application?

**Comment by yajna-pandith** [comment]
Hi @adecaro Not specifically, but I am looking for good first issues to enhance my application prospects.

**Comment by yajna08** [comment]
Sure

**Comment by adecaro** [comment]
not needed
