### ISSUE TITLE
Log Level

### ISSUE THREAD

**Issue by Virus-Syl** [hyperledger-labs/fabric-smart-client#386]
when i set log level as warning or error and exec start ,program panic. My topology like this:
<img width="604" alt="image" src="https://user-images.githubusercontent.com/21098163/190575565-eef3fe84-1010-44b8-95e2-f7bcac9dcf6e.png">

2022-09-16 14:26:35.964 CST [nwo.runner] Run -> INFO 015 running [fabric.default-OrdererOrg.orderer] with ginkgo stdout/stderr
panic: Timed out after 1.002s.
Error: Exit must be passed a gexec.Exiter (Missing method ExitCode() int) Got:
    <int>: -1

goroutine 69 [running]:
github.com/hyperledger-labs/fabric-smart-client/integration.failMe({0xc000052680?, 0x16?}, {0xc00072d9f8?, 0x5?, 0x5?})
        /Users/shengyulong/workspace/go/src/github.com/hyperledger-labs/fabric-smart-client/integration/integration.go:335 +0x2d
github.com/onsi/gomega/internal.(*AsyncAssertion).match.func1({0x4cb76f4, 0x9})
        /Users/shengyulong/workspace/go/pkg/mod/github.com/onsi/gomega@v1.19.0/internal/async_assertion.go:184 +0x31d
github.com/onsi/gomega/internal.(*AsyncAssertion).match(0xc0006440a0, {0x4f344d0, 0xc000638018}, 0x1, {0x0, 0x0, 0x0})
        /Users/shengyulong/workspace/go/pkg/mod/github.com/onsi/gomega@v1.19.0/internal/async_assertion.go:206 +0x598
github.com/onsi/gomega/internal.(*AsyncAssertion).Should(0xc0006440a0, {0x4f344d0, 0xc000638018}, {0x0, 0x0, 0x0})
        /Users/shengyulong/workspace/go/pkg/mod/github.com/onsi/gomega@v1.19.0/internal/async_assertion.go:107 +0x6b
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/common/runner.(*Runner).Run(0xc0002986c0, 0xc0000a8660, 0xc000644000?)
        /Users/shengyulong/workspace/go/src/github.com/hyperledger-labs/fabric-smart-client/integration/nwo/common/runner/runner.go:140 +0x10c4
github.com/tedsuo/ifrit.(*process).run(0xc0004e40c0)
        /Users/shengyulong/workspace/go/pkg/mod/github.com/tedsuo/ifrit@v0.0.0-20191009134036-9a97d0632f00/process.go:71 +0x31
created by github.com/tedsuo/ifrit.Background
        /Users/shengyulong/workspace/go/pkg/mod/github.com/tedsuo/ifrit@v0.0.0-20191009134036-9a97d0632f00/process.go:49 +0x125

**Comment by adecaro** [comment]
Hi @Virus-Syl , good catch.
Indeed, we need at least `info` to allow NWO to catch a log line that signals that the node has started.

Is there a special reason why you want to have 'error` there?

**Comment by adecaro** [comment]
oh, this is interesting. 
@mbrandenburger, do you want to jump in here? 
@Virus-Syl , do you have more info on the memory leak that can help us?

**Comment by Virus-Syl** [comment]
<img width="571" alt="image" src="https://user-images.githubusercontent.com/21098163/190989622-1ed35620-081d-4428-ac76-3b849defd978.png">
i rename iou as rbcsn

**Comment by adecaro** [comment]
@Virus-Syl , any update on this?

**Comment by adecaro** [comment]
closing this, it is too old
