### ISSUE TITLE
Connect to remote fabric network

### ISSUE THREAD

**Issue by Virus-Syl** [hyperledger-labs/fabric-smart-client#391]
Does fsc support connect to remote fabric network

**Comment by adecaro** [comment]
Hi @Virus-Syl, 

Of course, an FSC node can connect to multiple Fabric networks at the same time. It is all about configuration.

@mbrandenburger is taking the exercise to show step by step how this is happening: https://github.com/hyperledger-labs/fabric-smart-client/pull/382 

Maybe we can move the discussion to Discord and close this thread. What do you think?

**Comment by Virus-Syl** [comment]
ok, no problem
