### ISSUE TITLE
Should not have to use replace in go.mod to build a simple example

### ISSUE THREAD

**Issue by davidkel** [hyperledger-labs/fabric-smart-client#395]
As a user I want to create a single fabric smart client application that consists of 1 or more nodes.
I should be able to declare my dependency on fabric-smart-client as that is the only direct dependency I have as follows

```
module myfsc

go 1.17

require (
	github.com/hyperledger-labs/fabric-smart-client v0.0.0-20220829121531-bfb66997d570
	github.com/pkg/errors v0.9.1
)
```

however this fails due to various dependency clashes and the only way to resolve it appears to be to add the following replacements

```
replace (
	github.com/fsouza/go-dockerclient => github.com/fsouza/go-dockerclient v1.4.1
	github.com/go-kit/kit => github.com/go-kit/kit v0.7.0
	github.com/hyperledger/fabric => github.com/hyperledger/fabric v1.4.0-rc1.0.20210722174351-9815a7a8f0f7
	github.com/hyperledger/fabric-protos-go => github.com/hyperledger/fabric-protos-go v0.0.0-20201028172056-a3136dde2354
	go.etcd.io/etcd => go.etcd.io/etcd v0.5.0-alpha.5.0.20181228115726-23731bf9ba55
)
```

I am guessing that this comes about because the fsc code base has not kept upto date with the fabric code base in some way.

There are 2 issues here, 1 short team and 1 long term
short term issue: The replace information should be documented (not hidden somewhere examples as this is a definite usability requirement)
long term issue: The need to specify replacements should be removed and there needs to be a detachment from the fabric code base. I didn't think fabric code was designed to be imported or meant to be imported.

**Comment by adecaro** [comment]
Hi @davidkel , very interesting points here.

Regarding the dependency to Fabric, I think it is clear there are many components inside Fabric that can be decoupled from the Fabric repo like we did for Idemix that is now here https://github.com/IBM/idemix. 
The BCCSP is a clear example, the entire MSP folder is another. These are components that can be reused elsewhere.

So, given the current situation, what do you suggest? Should we copy the code we use from the Fabric repo to the FSC repo?

**Comment by mbwhite** [comment]
I've hit the same today, and so far have had to use 
```
replace (
        github.com/go-kit/kit => github.com/go-kit/kit v0.7.0
        github.com/hyperledger/fabric => github.com/hyperledger/fabric v1.4.0-rc1.0.20210722174351-9815a7a8f0f7
        github.com/hyperledger/fabric-protos-go => github.com/hyperledger/fabric-protos-go v0.0.0-20201028172056-a3136dde2354
)
```

This is _just_ for compilation - I've not done anything functional. Engineering wise this makes me very very nervous and concerned about how fragile the system is. For example the go-kit/kit library at that version is 6 years old.  The considerations for security patches and any knock-on effects are concerning for example. 

@adecaro copying code should be a last resort - and copying anything of notable size is indicative of large scale architectural issues.  For example it could mean that the original is broken and not being fixed or has a badly managed external interface.


"We are were we are" - best way is to move forward and define good semver on external interfaces on all components - and if needed make those interfaces if they don't already exist.  Any code that bypasses an exposed interface and goes to internals will, eventually, fail.

**Comment by denyeart** [comment]
The intent of the [hyperledger/fabric-lib-go](https://github.com/hyperledger/fabric-lib-go) repository was to hold common code that would be used across the Fabric family repositories. So I think the right thing to do would be to move things like BCCSP and MSP to this common code repository. I think BCCSP has evolved since v1.4, so it likely won't be a trivial exercise to pull it out into a common library that would be used by Fabric, Fabric-CA, and Fabric Smart Client (Fabric uses the latest BCCSP code while Fabric-CA and FSC use the v1.4 version). This would be an opportunity to restructure BCCSP. Perhaps Fabric v3.0 would use the restructured BCCSP along with Fabric-CA and FSC.

There are some other Fabric libraries used by Fabric-CA and FSC as well. BCCSP seems to be the one with the largest surface area and usage though.

While not trivial, I think this exercise would be important if we think Fabric-CA and FSC will be supported long term.

**Comment by adecaro** [comment]
@denyeart , good points. I have a gut feeling that it should be easy to move out the BCCSP and MSP package. 
@ale-linux already did that for idemix. 
@ale-linux , what's your take?

**Comment by davidkel** [comment]
As far as this issue is concerned, it's been addressed as there is no need to specify replace blocks anymore.

What has been discussed here is the issue where FSC uses the fabric codebase as an api but fabric is not designed to be embedded as an api, so there needs to be a long term solution for this given that FSC modelled it's implementation on fabric artifacts such as MSP and BCCSP. Options are

1. copy the code from fabric
2. see if fabric will move the relevant parts into a proper versioned api for applications to re-use
3. FSC to implement their own concepts rather than replicating what fabric did

(I'm guessing 3 is a non starter but thought I would mention it anyway)

**Comment by adecaro** [comment]
@davidkel , can we close this?
