### ISSUE TITLE
Web Server should be able to be configured to not accept client requests to call views

### ISSUE THREAD

**Issue by davidkel** [hyperledger-labs/fabric-smart-client#408]
The Web Server has multiple purposes
1. Accept client requests to call views
2. respond to /version request
3. respond to /healthz request
4. respond to /metrics request (prometheus)

Currently the web server can either be enabled with or without tls but if tls is enabled it will only work with mutual tls. Without TLS is really there for test environments. mutual tls is being mandated as an authorisation mechanism (rather than using basic auth for example, in a similar manner to the way that osnadmin works on fabric). 

However this makes K8s checks for /healthz difficult if not impossible to manage for example. 

Admins should have the option to not use mutualTLS but if it's disabled then maybe we should disable the ability to call views but still allow access to the other routes for node management.

**Comment by yacovm** [comment]
> mutual tls is being mandated as an authorisation mechanism (rather than using basic auth for example, in a similar manner to the way that osnadmin works on fabric).

> However this makes K8s checks for /healthz difficult if not impossible to manage for example.

No, it does not. You can make mutual TLS optional and then enforce checks for all endpoints except /healthz.

**Comment by davidkel** [comment]
@yacovm In the webserver I can't find anything detailing how to make mutualtls optional, all I can find is to turn tls off altogether which I see disables the ability to call views. Can you provide more information on how I turn off mutual tls but keep tls itself ? Looking at the code it's not obvious (unless just not specifying something in core.yaml) actually controls that. In which case that would be useful to know and I can include it as part of the information I am putting together about the contents of core.yaml
