### ISSUE TITLE
SDK cannot be integrated in existing application without taking over commandline flags

### ISSUE THREAD

**Issue by arner** [hyperledger-labs/fabric-smart-client#477]
When integrating the FSC SDK into an existing golang application, as described [here](https://github.com/hyperledger-labs/fabric-token-sdk/blob/main/samples/fungible/README.md#token-sdk-fungible-tokens-the-basics), the SDK requires certain CLI flags to be set. If the existing application is not started as follows: `./myapp node start`, the FSC node doesn't start.

It also removes the possibility for the golang application to use their own flags:

```
./myapp -p 9200

Error: unknown shorthand flag: 'p' in -p
Usage:
  peer [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  node        Operate a fabric smart client node: start.
  version     Print the fabric smart client version.

Flags:
  -h, --help   help for peer

Use "peer [command] --help" for more information about a command.
```

Starting the FSC node should be decoupled from the way it's started (via CLI or code).

**Comment by adecaro** [comment]
@arner , very good point. Can you show me the code you use to embed the token-sdk in your app?

**Comment by arner** [comment]
```
var FSC = node.NewFromConfPath(dir)

func InitializeFSCAndTokenSDK(callback func() error) {
	// Install the required SDKs
	succeedOrPanic(FSC.InstallSDK(fabric.NewSDK(FSC)))
	succeedOrPanic(FSC.InstallSDK(tokensdk.NewSDK(FSC)))

	// Execute the stack
	FSC.Execute(callback)
	succeedOrPanic(FSC.Start())
}

func succeedOrPanic(err error) {
	if err != nil {
		fmt.Println(err)
		fmt.Println("Failed initializing Token SDK")

		panic(err)
	}
}
```

**Comment by adecaro** [comment]
Ahh, got it. So the proper `node` package to use is: `hyperledger-labs/fabric-smart-client/pkg/node`

**Comment by arner** [comment]
How do I instruct the node to start listening, and where do I register the views? `hyperledger-labs/fabric-smart-client/pkg/node` does not have .Execute (and node.listen is not exposed).

**Comment by arner** [comment]
Oh, right! After some trial and error I realised it's actually pretty simple, you can just first fsc.Start() and then register your views right after that - no need for the .Execute callback. Thanks
