### ISSUE TITLE
staticcheck: reduce warnings

### ISSUE THREAD

**Issue by adecaro** [hyperledger-labs/fabric-smart-client#50]

**Comment by mbrandenburger** [comment]
#305 Replaced golint with staticchecks.

**Comment by mbrandenburger** [comment]
An assessment of the current code is needed and staticchecks issues should be resolved.

**Comment by adecaro** [comment]
Shall address also this?

`go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.`

**Comment by alexandrosfilios** [comment]
All PR's included
- [ ] ST1005
- [ ] ST1019
- [ ] S1023
- [ ] SA1019
- [ ] SA1019
- [ ] ST1001
- [ ] S1000
- [ ] S1034
- [ ] S1039
- [ ] S1011
- [ ] SA4023
- [ ] S021, S1038, S1025, SA4009, S1005, SA9003
- [ ] SA4004
- [ ] SA9005
- [ ] SA4006
