### ISSUE TITLE
Propagating Context from Microservices: A Proposal for fabric-smart-client Improvement

### ISSUE THREAD

**Issue by PERSEJOZA** [hyperledger-labs/fabric-smart-client#599]
We are implementing OpenTelemetry for observability in our solution, but we have identified a blind spot. Currently, we are unable to obtain information about delays and propagate trace information. This is due to the fact that the InitiateView method of the ViewManager does not support context propagation. As a result, we are unable to create a complete and accurate picture of the system's behavior, starting from the controller or other microservices within the solution.

We would greatly benefit from the fabric-smart-client library supporting the propagation of context instead of creating a new one. This would enable the propagation of trace information from the microservice. To achieve this, we suggest either adding a new method or modifying the existing viewManager.InitiateView() method to accept a context.

**Comment by arner** [comment]
Implemented in https://github.com/hyperledger-labs/fabric-smart-client/commit/1564d268fe241d420137023da87d598b89a33304

**Comment by arner** [comment]
Opening this up again; another way to use FSC is to InitiateContext with a view first, and then pass around the resulting view.Context. That way should also support to derive a view.Context from an existing context.Context.

**Comment by adecaro** [comment]
@alexandrosfilios , what do you think of this?

**Comment by arner** [comment]
@adecaro this is resolved if we merge https://github.com/hyperledger-labs/fabric-smart-client/pull/644

**Comment by adecaro** [comment]
addressed
