### ISSUE TITLE
KVS versioning abstraction

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-smart-client#665]
The current vault impl uses by default the Fabric RWs versioning protos to capture the version of key-value pairs. As this works well for Fabric, other platforms, such as Orion, may need to adopt that versioning scheme. 

This issue proposes an KVS versioning abstraction used by the vault, and thereby, make it independent of the actual platform in use. For instance, the vault could store the version information as bytes and the platform provides a marshaller impl to convert the bytes into the proper format according to the platform.

**Comment by adecaro** [comment]
addressed
